!define CC_SWITCH_INSTALLER_HOOK_DIR "${__FILEDIR__}"

!macro NSIS_HOOK_POSTINSTALL
  SetOutPath "$INSTDIR"
  File /oname=THIRD_PARTY_NOTICES.md "${CC_SWITCH_INSTALLER_HOOK_DIR}\..\..\THIRD_PARTY_NOTICES.md"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  Delete "$INSTDIR\THIRD_PARTY_NOTICES.md"
!macroend
